### ISSUE TITLE
Property evaluation in templates

### ISSUE THREAD

**Issue by kokujin** [pluma/obs#1]
Hi there!

Thanks for creating Obs. I would like to use Obs to "bridge" my Node.js backend to my frontend UI in some places, in short, a quick example:

// My middleware
var testObs = obs.prop(2);
db = require("mongoskin").db('mongodb://localhost', {
  database: 'db-dev',
  safe: true,
  strict: false
});

module.exports = function(config) {
    return function(req, res, next) {
        res.locals.appName = config.app.name;  
        res.locals.testObs = testObs;
        res.db = db;
        next();
    }
}

//In my template:
<a href="/gallery">Gallery {{ testObs.prop() }}</a>

This errors out with this traceback;
".........TypeError: string is not a function"

This is strange because I can call plain functions or other object methods without any problems in my templates. Any idea what exactly I am doing wrong? I am using the latest Node.js, Express.js and Nunchucks templating engine. Thanks!

**Comment by pluma** [comment]
Thanks for filing this report.

I have no experience with Nunchucks, but I think the issue is in how you try to read from the observable. From what I can see, you are creating an observable property (short "observable") called `testObs`. An observable is a function that will return its "saved" value when called with no arguments or replace it when passed a new value. In other words: to read from an observable, you just need to call it like a function.

In your template you are trying to access the `prop` property of the observable `testObs`. From your example code, this should be undefined. I'm not sure why the traceback complains about a string instead.

Try the following in your template:

```
Gallery {{ testObs() }}
```

If you are not sure how observable properties behave, I would recommend experimenting with them in Node's REPL (i.e. the console you get when calling the Node executable directly in the shell).

**Comment by kokujin** [comment]
Thanks, it works as expected. I took another look at the docs :)
