### ISSUE TITLE
TypeError: Cannot call method 'PubSub' of undefined

### ISSUE THREAD

**Issue by nkcmr** [pluma/obs#2]
I am attempting to use `obs` in a browser environment and it keeps throwing this error when I include the prepackaged script (with `aug` and `sublish`).

![Screen Shot 2013-04-08 at 6 06 35 PM](https://f.cloud.github.com/assets/1791521/354228/9b385d8e-a098-11e2-8f1a-e8a96e8555fe.png)

**Comment by pluma** [comment]
Thanks for bringing this to my attention. It's a problem in sublish, actually. I originally wanted to call the package `pubsub`, but that name was obviously taken. I thought I had changed all occurrences of the old name, but I missed the one in the global assignment because the testcases use node.js (and thus `exports` and `require`).

**Comment by pluma** [comment]
There was another problem (the global `sublish` object was not passed to the factory function).

It seems to work now.

**Comment by nkcmr** [comment]
Thanks for the quick response! This is the best observables solution I have come across. Keep up the amazing work! :+1:
